<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>DistSys.Shared.Discovery</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Consul" Version="1.8.0" />
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="8.0.1" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="8.0.0" />
    <PackageReference
      Include="Microsoft.Extensions.DependencyInjection.Abstractions"
      Version="8.0.2"
    />
  </ItemGroup>

  <Import Project="../../../GlobalSettings.msbuild" />
</Project>
